name: Crop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Private Repository
        uses: actions/checkout@v3.5.2
        with:
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Rclone
        uses: AnimMouse/setup-rclone@v1.5.1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Run External Workflow
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          file: ${{ matrix.file }}
        run: |
          chmod +x script_c.sh
          ./script_c.sh
