name: Use External Workflow

on:
  workflow_dispatch:

jobs:
  use-external-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v4.2.0
        with:
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Rclone
        uses: AnimMouse/setup-rclone@v1.10.2
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: ffmpeg

      - name: Run External Workflow
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          chmod +x script.sh
          ./script.sh
